# WX configuration
#------------------------------------------------------------------------------------------
# Config for request fields and WX mandatory fields (as below) in sending message out
# - header
#   + Cookie
# - BaseRequest
#   + Uin
#   + Sid
#   + Skey
#   + DeviceID
#------------------------------------------------------------------------------------------

# Wx Urls #
baseUrl: "https://wx2.qq.com/cgi-bin/mmwebwx-bin" #wx/wx2
baseUploadUrl: "https://file2.wx.qq.com/cgi-bin/mmwebwx-bin" #file/file2
getContactUrl: "/webwxgetcontact"
batchGetContactUrl: "/webwxbatchgetcontact"
sendMsgUrl: "/webwxsendmsg"
getWebwxInit: "/webwxinit"
getWebwxSync: "/webwxsync"
getWebwxOplog: "/webwxoplog"
syncCheck: "/synccheck"
webWxUploadMedia: "/webwxuploadmedia"
webwxsendmsgimg: "/webwxsendmsgimg"

contentType: "application/json;charset=UTF-8"
connection: "keep-alive"

cookie: "pac_uid=1_296289710; 3g_guest_id=-8961351989443137536; tvfe_boss_uuid=224aebb765600aff; webwxuvid=d5c7210588bfb1815776a1a12ea2fc6ad8ad107bbc63e7972999bef75002468235e8046a7c5090f6eca495606af3d254; p_o2_uin=296289710; o_cookie=296289710; pgv_pvid=701650048; pgv_pvi=7734875136; ptui_loginuin=2693938513; RK=1AOu4/milz; ptcz=04842e212b9539964bfdcf44e985b5c98d3fdfa4dea4c23eafeb7b6b52d80fa6; pt2gguin=o2693938513; pgv_si=s505092096; webwx_auth_ticket=CIsBEP2Ov5MMGoAB08mdWyCcV8fc3HACVtuGJxa5zMBivk9gxOnWAc/9OH7ZWgd0RV5lRXk8Zdd9pLgarw/ytCFrHwCNmVq1bWJxRiiGtzAkxYJffI49IeqJPjl0cx9OjNBmbJxH2jTIktY2ojJZnNFSJf2JbpBwXtVaHVwewOz5anWLPE4Paw30cpI=; mm_lang=zh_CN; MM_WX_NOTIFY_STATE=1; MM_WX_SOUND_STATE=1; wxloadtime=1483001219_expired; wxpluginkey=1482971761; wxuin=3405351523; wxsid=zHKPOM0RuRL4Fz1Z; webwx_data_ticket=gSfAvYYv1rDL+w8/Juhr32zb"

Uin: "3405351523"
Sid: "zHKPOM0RuRL4Fz1Z"
Skey: "@crypt_bfbdd636_7ff15c3a927377d455f30ea89716f4d5"
DeviceID: "e623440071044992"

listenOnAllGroups: true
listenGroupNameList: [""]

# Media
imageDir: ""
imageDirForReply: ""
sendImageGroupNameList: [""]

# input maintainer name
# Hubot will notify maintainer if encounter issues
maintainerName: "seawalker" 

foreverDaemon: true

# WxHubot Configurations
# unit:
  # s = seconds
  # m = milliseconds
  # u = microseconds
  # n = nanoseconds
webWxSyncInterval: "2s"
syncCheckInterval: "30s"
reportHealthInterval: "21600s"

logToFile: true
wxLogPath: "/data/iflyrd/logs/wxhubot.log"
