// Generated by CoffeeScript 1.10.0
(function() {
  var redis = require("redis");
  var client = redis.createClient();

  client.on("error", function (err) {
    console.log("Error " + err);
  });

  var redis_set = function(key, val, callback) {
    client.set(key, val, function (err, reply) {
      callback(reply, null);
    });
  };

  var redis_get = function(key, callback) {
    client.get(key, function(err, reply) {
      callback(reply, null);
    });
  };

  module.exports = {
    get: redis_get,
    set: redis_set
  };

}).call(this);